version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    environment: 
      - cluster.name=es-docker-cluster
      - node.name=docker-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
  elasticsearch-head:
    image: slydeveloper/elasticsearch-head:latest
    ports:
      - "9100:9100"
    container_name: elasticsearch-head